In [3]:
import pandas as pd
from sqlalchemy import create_engine

# Parámetros de conexión
user = "coniitic_registro"
password = "G3!+GUyN-1bXP+]x"
host = "coniiti.com"
database = "coniitic_registro"

engine = create_engine(
    f"mysql+pymysql://{user}:{password}@{host}/{database}"
)

# Consulta (cambia el nombre si tu tabla no se llama regeventos)
query = "SELECT * FROM regeventos"

df = pd.read_sql(query, engine)

df.head()

,id,qr_Acceso,nombres,apellidos,email,telefono,tipo_documento,num_documento,genero,pais,ucatolica,rol,programa,profesion,nom_Evento,qr_validado,fecha_uso,fecha_registro
0,4,OXL3IHNL6KFN8KGPQE,yenny,hernandez,jphernandez@ucatolica.edu.co,3168232187,CC,1024486270,Femenino,Colombia,S,Administrativo,Facultad de Ingeniería,Adminsitradora financiera,Del reto a la solución: Innovar con Design Thi...,1,2025-10-01 15:05:30,2025-09-30 13:58:57
1,5,5RBN17AAE2OOL47485,Diego Fernando,Meléndez Suárez,dfmelendez@ucatolica.edu.co,3183530817,CC,91284150,Masculino,Colombia,S,Profesor/Administrativo,Esp. en Ingeniería de Pavimentos,Ingeniero Civil,Workshop: Diseños de mezcla de concreto bajo l...,0,NaT,2025-09-30 18:15:53
2,6,R2SV7WXIAQ63Y1GIL3,Diego Fernando,Meléndez Suárez,dfmelendez@ucatolica.edu.co,3183530817,CC,91284150,Masculino,Colombia,S,Profesor/Administrativo,Esp. en Ingeniería de Pavimentos,Ingeniero Civil,Conferencia : Arquitectura y diseño sostenible...,0,NaT,2025-09-30 18:31:52
3,7,P58X4OTXBNFUAQIJ54,Diego Fernando,Meléndez Suárez,dfmelendez@ucatolica.edu.co,3183530817,CC,91284150,Masculino,Colombia,S,Profesor/Administrativo,Esp. en Ingeniería de Pavimentos,Ingeniero Civil,Conferencia: Proyectos comprometidos con la so...,0,NaT,2025-09-30 18:32:43
4,8,MK8DW21CHVHXTGBAS5,Oscar Raul,Pinto Celis,orpinto@ucatolica.edu.co,3125812914,CC,91500261,Masculino,Colombia,S,Profesor/Administrativo,Esp. en Gerencia de Obras,Ingeniero Civil,Conferencia: Premio Nacional de Ingeniería: Re...,1,2025-10-02 14:05:02,2025-09-30 18:32:53

In [9]:
df['asistio'] = df['qr_validado'].map({1: "Sí", 0: "No"})

In [7]:
df['registro_hora'] = df['fecha_registro'].dt.hour

In [8]:
pd.get_dummies(df, columns=['genero','rol','pais'], drop_first=True)

,id,qr_Acceso,nombres,apellidos,email,telefono,tipo_documento,num_documento,ucatolica,programa,...,rol_Profesor/Administrativo,rol_Profesor/Egresado,pais_Bolivia,pais_Brasil,pais_Colombia,pais_Comoras,pais_Costa Rica,pais_México,pais_Perú,pais_Venezuela
0,4,OXL3IHNL6KFN8KGPQE,yenny,hernandez,jphernandez@ucatolica.edu.co,3168232187,CC,1024486270,S,Facultad de Ingeniería,...,False,False,False,False,True,False,False,False,False,False
1,5,5RBN17AAE2OOL47485,Diego Fernando,Meléndez Suárez,dfmelendez@ucatolica.edu.co,3183530817,CC,91284150,S,Esp. en Ingeniería de Pavimentos,...,True,False,False,False,True,False,False,False,False,False
2,6,R2SV7WXIAQ63Y1GIL3,Diego Fernando,Meléndez Suárez,dfmelendez@ucatolica.edu.co,3183530817,CC,91284150,S,Esp. en Ingeniería de Pavimentos,...,True,False,False,False,True,False,False,False,False,False
3,7,P58X4OTXBNFUAQIJ54,Diego Fernando,Meléndez Suárez,dfmelendez@ucatolica.edu.co,3183530817,CC,91284150,S,Esp. en Ingeniería de Pavimentos,...,True,False,False,False,True,False,False,False,False,False
4,8,MK8DW21CHVHXTGBAS5,Oscar Raul,Pinto Celis,orpinto@ucatolica.edu.co,3125812914,CC,91500261,S,Esp. en Gerencia de Obras,...,True,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2435,2443,2N0I79IEA0XE7O53BP,Fabiola Patricia,Mejia,fpmejia92@ucatolica.edu.co,3158828428,CC,52110030,S,Esp. en Seguridad de la Información,...,False,False,False,False,True,False,False,False,False,False
2436,2444,FYIPXR1XXJ50R4KX7X,David,Diaz,ddiaz88@ucatolica.edu.co,3113238377,CC,1094905240,S,Esp. en Seguridad de la Información,...,False,False,False,False,True,False,False,False,False,False
2437,2445,N0Q7HEBNXACGX113OT,Santiago,Rozo Moreno,srozo49@ucatolica.edu.co,3246094797,CC,1016824414,S,Ingeniería Civil,...,False,False,False,False,True,False,False,False,False,False
2438,2446,VOHM4DN5T8R767RMHF,Santiago,Rozo Moreno,srozo49@ucatolica.edu.co,3246094797,CC,1016824414,S,Ingeniería Civil,...,False,False,False,False,True,False,False,False,False,False
2439,2447,Q7F8OVMTMRBMAJ8TRJ,Santiago,Rozo Moreno,srozo49@ucatolica.edu.co,3246094797,CC,1016824414,S,Ingeniería Civil,...,False,False,False,False,True,False,False,False,False,False